version: '3.1'
services:
  springboot-app:
    ports:
      - "9090:9090"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mycassandra
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
