version: '3.1'
services:
#  springboot-app:
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
